  0         LOADL        0
  1         CALL         newarr  
  2         CALL         L10
  3         HALT   (0)   
  4         LOADL        -1
  5         LOADL        2
  6         CALL         newobj  
  7         LOAD         3[LB]
  8         LOADL        1
  9         LOADL        -1
 10         LOADL        2
 11         CALL         newobj  
 12         CALL         fieldupd
 13         LOAD         3[LB]
 14         LOADL        0
 15         LOADL        5
 16         CALL         fieldupd
 17         LOAD         3[LB]
 18         LOADL        1
 19         CALL         fieldref
 20         LOADL        0
 21         LOADL        1
 22         CALL         fieldupd
 23         LOAD         3[LB]
 24         LOADL        0
 25         CALL         fieldref
 26         LOAD         3[LB]
 27         LOADL        1
 28         CALL         fieldref
 29         LOADL        0
 30         CALL         fieldref
 31         CALL         add     
 32         STORE        4[LB]
 33         LOAD         4[LB]
 34         CALL         putintnl
 35         RETURN (0)   1
 36         LOADL        0
 37         LOADL        1
 38         LOADL        0
 39         LOADL        1
 40  L10:   LOADL        -1
 41         LOADL        2
 42         CALL         newobj  
 43         LOAD         3[LB]
 44         LOADL        1
 45         LOADL        -1
 46         LOADL        2
 47         CALL         newobj  
 48         CALL         fieldupd
 49         LOAD         3[LB]
 50         LOADL        0
 51         LOADL        5
 52         CALL         fieldupd
 53         LOAD         3[LB]
 54         LOADL        1
 55         CALL         fieldref
 56         LOADL        0
 57         LOADL        1
 58         CALL         fieldupd
 59         LOAD         3[LB]
 60         LOADL        0
 61         CALL         fieldref
 62         LOAD         3[LB]
 63         LOADL        1
 64         CALL         fieldref
 65         LOADL        0
 66         CALL         fieldref
 67         CALL         add     
 68         STORE        4[LB]
 69         LOAD         4[LB]
 70         CALL         putintnl
 71         RETURN (0)   1
