  0         LOADL        0
  1         CALL         newarr  
  2         CALL         L10
  3         HALT   (0)   
  4         LOADL        -1
  5         LOADL        2
  6         CALL         newobj  
  7         LOAD         3[LB]
  8         LOADL        1
  9         LOADL        -1
 10         LOADL        2
 11         CALL         newobj  
 12         CALL         fieldupd
 13         LOAD         3[LB]
 14         LOADL        1
 15         CALL         fieldref
 16         LOADL        1
 17         LOAD         3[LB]
 18         CALL         fieldupd
 19         LOAD         3[LB]
 20         LOADL        1
 21         CALL         fieldref
 22         LOADL        1
 23         CALL         fieldref
 24         LOADL        0
 25         LOADL        7
 26         CALL         fieldupd
 27         LOAD         3[LB]
 28         LOADL        0
 29         CALL         fieldref
 30         STORE        4[LB]
 31         LOAD         4[LB]
 32         CALL         putintnl
 33         RETURN (0)   1
 34         LOADL        0
 35         LOADL        1
 36         LOADL        0
 37         LOADL        1
 38  L10:   LOADL        -1
 39         LOADL        2
 40         CALL         newobj  
 41         LOAD         3[LB]
 42         LOADL        1
 43         LOADL        -1
 44         LOADL        2
 45         CALL         newobj  
 46         CALL         fieldupd
 47         LOAD         3[LB]
 48         LOADL        1
 49         CALL         fieldref
 50         LOADL        1
 51         LOAD         3[LB]
 52         CALL         fieldupd
 53         LOAD         3[LB]
 54         LOADL        1
 55         CALL         fieldref
 56         LOADL        1
 57         CALL         fieldref
 58         LOADL        0
 59         LOADL        7
 60         CALL         fieldupd
 61         LOAD         3[LB]
 62         LOADL        0
 63         CALL         fieldref
 64         STORE        4[LB]
 65         LOAD         4[LB]
 66         CALL         putintnl
 67         RETURN (0)   1
