  0         LOADL        0
  1         CALL         newarr  
  2         CALL         L11
  3         HALT   (0)   
  4         LOADL        0
  5  L10:   LOADA        0[OB]
  6         LOADL        0
  7         LOADA        0[OB]
  8         LOADL        0
  9         CALL         fieldref
 10         CALL         fieldref
 11         LOAD         -1[LB]
 12         CALL         add     
 13         CALL         fieldupd
 14         LOADA        0[HB]
 15         LOADL        0
 16         LOADL        2
 17         LOADA        0[OB]
 18         LOADL        0
 19         CALL         fieldref
 20         CALL         fieldref
 21         CALL         add     
 22         CALL         fieldupd
 23         RETURN (0)   1
 24         LOADL        0
 25         LOADA        0[HB]
 26         LOADL        0
 27         LOADL        3
 28         CALL         fieldupd
 29         LOADL        4
 30         LOADA        0[HB]
 31         CALLI        L10
 32         LOADA        0[HB]
 33         LOADL        0
 34         CALL         fieldref
 35         LOADA        0[OB]
 36         LOADL        0
 37         CALL         fieldref
 38         CALL         fieldref
 39         CALL         add     
 40         LOADL        7
 41         CALL         add     
 42         STORE        3[LB]
 43         LOAD         3[LB]
 44         CALL         putintnl
 45         RETURN (0)   1
 46  L11:   LOADA        0[HB]
 47         LOADL        0
 48         LOADL        3
 49         CALL         fieldupd
 50         LOADL        4
 51         LOADA        0[HB]
 52         CALLI        L10
 53         LOADA        0[HB]
 54         LOADL        0
 55         CALL         fieldref
 56         LOADA        0[OB]
 57         LOADL        0
 58         CALL         fieldref
 59         CALL         fieldref
 60         CALL         add     
 61         LOADL        7
 62         CALL         add     
 63         STORE        3[LB]
 64         LOAD         3[LB]
 65         CALL         putintnl
 66         RETURN (0)   1
