  0         LOADL        0
  1         CALL         newarr  
  2         CALL         L11
  3         HALT   (0)   
  4         LOADL        2
  5         LOADL        2
  6         LOADL        5
  7         CALL         mult    
  8         LOADL        3
  9         CALL         sub     
 10         CALL         newarr  
 11         STORE        4[LB]
 12         LOAD         4[LB]
 13         LOADL        0
 14         LOADL        13
 15         CALL         arrayupd
 16         LOAD         4[LB]
 17         LOAD         3[LB]
 18         LOADL        2
 19         CALL         sub     
 20         CALL         arrayref
 21         LOAD         3[LB]
 22         CALL         gt      
 23         STORE        5[LB]
 24         LOAD         5[LB]
 25         JUMPIF (0)   L10
 26         LOAD         4[LB]
 27         LOAD         3[LB]
 28         LOADL        1
 29         CALL         sub     
 30         LOAD         4[LB]
 31         LOAD         3[LB]
 32         LOADL        2
 33         CALL         sub     
 34         CALL         arrayref
 35         CALL         arrayupd
 36  L10:   RETURN (0)   1
 37  L11:   LOADL        2
 38         LOADL        2
 39         LOADL        5
 40         CALL         mult    
 41         LOADL        3
 42         CALL         sub     
 43         CALL         newarr  
 44         STORE        4[LB]
 45         LOAD         4[LB]
 46         LOADL        0
 47         LOADL        13
 48         CALL         arrayupd
 49         LOAD         4[LB]
 50         LOAD         3[LB]
 51         LOADL        2
 52         CALL         sub     
 53         CALL         arrayref
 54         LOAD         3[LB]
 55         CALL         gt      
 56         STORE        5[LB]
 57         LOAD         5[LB]
 58         JUMPIF (0)   L12
 59         LOAD         4[LB]
 60         LOAD         3[LB]
 61         LOADL        1
 62         CALL         sub     
 63         LOAD         4[LB]
 64         LOAD         3[LB]
 65         LOADL        2
 66         CALL         sub     
 67         CALL         arrayref
 68         CALL         arrayupd
 69  L12:   RETURN (0)   1
